import monkey1 from "assets/monkeys/1.jpg";
import monkey2 from "assets/monkeys/2.jpg";
import monkey3 from "assets/monkeys/3.jpg";
import monkey4 from "assets/monkeys/4.jpg";
import monkey5 from "assets/monkeys/5.jpg";
import monkey6 from "assets/monkeys/6.jpg";
import monkey7 from "assets/monkeys/7.jpg";
import monkey8 from "assets/monkeys/8.jpg";
import monkey9 from "assets/monkeys/9.jpg";
import monkey10 from "assets/monkeys/10.jpg";
import monkey11 from "assets/monkeys/11.jpg";
import monkey12 from "assets/monkeys/12.jpg";
import monkey13 from "assets/monkeys/13.jpg";
import monkey14 from "assets/monkeys/14.jpg";
import monkey15 from "assets/monkeys/15.jpg";
import monkey16 from "assets/monkeys/16.jpg";
import monkey17 from "assets/monkeys/17.jpg";
import monkey18 from "assets/monkeys/18.jpg";
import monkey19 from "assets/monkeys/19.jpg";
import monkey20 from "assets/monkeys/20.jpg";
import monkey21 from "assets/monkeys/21.jpg";
import monkey22 from "assets/monkeys/22.jpg";
import monkey23 from "assets/monkeys/23.jpg";
import monkey24 from "assets/monkeys/24.jpg";
import monkey25 from "assets/monkeys/25.jpg";
import monkey26 from "assets/monkeys/26.jpg";
import monkey27 from "assets/monkeys/27.jpg";
import monkey28 from "assets/monkeys/28.jpg";
import monkey29 from "assets/monkeys/29.jpg";
import monkey30 from "assets/monkeys/30.jpg";
import monkey31 from "assets/monkeys/31.jpg";
import monkey32 from "assets/monkeys/32.jpg";
import monkey33 from "assets/monkeys/33.jpg";
import monkey34 from "assets/monkeys/34.jpg";
import monkey35 from "assets/monkeys/35.jpg";
import monkey36 from "assets/monkeys/36.jpg";
import monkey37 from "assets/monkeys/37.jpg";
import monkey38 from "assets/monkeys/38.jpg";
import monkey39 from "assets/monkeys/39.jpg";
import monkey40 from "assets/monkeys/40.jpg";

const MONKEYS = [
  { imageSrc: monkey1 },
  { imageSrc: monkey2 },
  { imageSrc: monkey3 },
  { imageSrc: monkey4 },
  { imageSrc: monkey5 },
  { imageSrc: monkey6 },
  { imageSrc: monkey7 },
  { imageSrc: monkey8 },
  { imageSrc: monkey9 },
  { imageSrc: monkey10 },
  { imageSrc: monkey11 },
  { imageSrc: monkey12 },
  { imageSrc: monkey13 },
  { imageSrc: monkey14 },
  { imageSrc: monkey15 },
  { imageSrc: monkey16 },
  { imageSrc: monkey17 },
  { imageSrc: monkey18 },
  { imageSrc: monkey19 },
  { imageSrc: monkey20 },
  { imageSrc: monkey21 },
  { imageSrc: monkey22 },
  { imageSrc: monkey23 },
  { imageSrc: monkey24 },
  { imageSrc: monkey25 },
  { imageSrc: monkey26 },
  { imageSrc: monkey27 },
  { imageSrc: monkey28 },
  { imageSrc: monkey29 },
  { imageSrc: monkey30 },
  { imageSrc: monkey31 },
  { imageSrc: monkey32 },
  { imageSrc: monkey33 },
  { imageSrc: monkey34 },
  { imageSrc: monkey35 },
  { imageSrc: monkey36 },
  { imageSrc: monkey37 },
  { imageSrc: monkey38 },
  { imageSrc: monkey39 },
  { imageSrc: monkey40 },
];

export default MONKEYS;
